"""init_migration

Revision ID: e37cc3e97b04
Revises: 
Create Date: 2024-10-08 21:16:20.155858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37cc3e97b04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('underground', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('house_num', sa.String(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('total_floor', sa.Integer(), nullable=False),
    sa.Column('total_meters', sa.Float(), nullable=False),
    sa.Column('living_meters', sa.Float(), nullable=False),
    sa.Column('kitchen_meters', sa.Float(), nullable=False),
    sa.Column('rooms_count', sa.Integer(), nullable=False),
    sa.Column('year_of_construction', sa.Integer(), nullable=False),
    sa.Column('house_material_type', sa.String(), nullable=False),
    sa.Column('commission', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('adv_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('amount_of_views', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('unpublish_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('views')
    op.drop_table('price')
    op.drop_table('advertisement')
    op.drop_table('object')
    op.drop_table('author')
    # ### end Alembic commands ###
