volumes:
  pgdata:

networks:
  net:

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net
    ports:
      - "5432:5432"  # Открываем порт для доступа к БД
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: python_app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    networks:
      - net
    ports:
      - "8000:8000"
